# Generated by Django 5.1.3 on 2024-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_modeluser_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modeluser",
            options={
                "permissions": [("can_block_user", "Can block user")],
                "verbose_name": "пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="modeluser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="modeluser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
