# Generated by Django 5.1.3 on 2024-11-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=250, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=250, verbose_name="Фамилия")),
                ("patronymic", models.CharField(blank=True, max_length=250, null=True, verbose_name="Отчество")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Коментарий")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальное имя формируется из фамилии и имени",
                        max_length=255,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "получателя рассылки",
                "verbose_name_plural": "Получатель рассылки",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Тема письма")),
                ("body_message", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "Сообщение",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "first_dispatch",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
                ),
                (
                    "end_dispatch",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="recipients", to="mailing.mailingrecipient", verbose_name="Получатели"
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_text",
                        to="mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылку",
                "verbose_name_plural": "Рассылка",
            },
        ),
        migrations.CreateModel(
            name="AttemptToSend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempts", models.DateTimeField(verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.BooleanField(choices=[(True, "Успешно"), (False, "Не успешно")], verbose_name="Статус"),
                ),
                ("server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "newsletter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailing.newsletter"),
                ),
            ],
            options={
                "verbose_name": "попытки рассылок",
                "verbose_name_plural": "Попытка рассылки",
            },
        ),
    ]
